# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['get_text', 'extract_tool_calls', 'tool_schema', 'Response', 'Chat', 'AsyncChat']

# %% ../nbs/00_core.ipynb #a868f037
"""lyca — Stateful Chat/AsyncChat for LiteRT-LM models."""

__all__ = ['Response', 'Chat', 'AsyncChat', 'get_text', 'extract_tool_calls', 'tool_schema']

# %% ../nbs/00_core.ipynb #5972659c
import atexit, asyncio, os, re
from dataclasses import dataclass, field
from functools import partial

import litert_lm
from toolslm.funccall import get_schema, mk_ns
from msglm import mk_msg, mk_msgs
from fastcore.utils import *
from fastcore.meta import store_attr, delegates, patch

# %% ../nbs/00_core.ipynb #f9cb70ad
def get_text(response: dict) -> str:
    "Extract text string from a LiteRT-LM response dict."
    for item in response.get('content', []):
        if item.get('type') == 'text': return item['text']
    return ''

# %% ../nbs/00_core.ipynb #6538e118
def extract_tool_calls(text: str) -> list[dict]:
    "Parse Gemma 4 <|tool_call>...<tool_call|> tokens from raw text."
    def cast(v):
        try: return int(v)
        except:
            try: return float(v)
            except: return {'true': True, 'false': False}.get(v.lower(), v.strip("'\"" ))
    return [{'name': n, 'arguments': {
                k: cast((v1 or v2).strip())
                for k, v1, v2 in re.findall(r'(\w+):(?:<\|"\|>(.*?)<\|"\|>|([^,}]*))', args)
             }}
            for n, args in re.findall(r'<\|tool_call>call:(\w+)\{(.*?)\}<tool_call\|>', text, re.DOTALL)]

# %% ../nbs/00_core.ipynb #be91a434
def tool_schema(f) -> dict:
    "Show toolslm JSON schema for function `f` (informational — lyca passes callables directly)."
    return get_schema(f, pname='parameters')

# %% ../nbs/00_core.ipynb #16e7ca37
@dataclass
class Response:
    "Return value from Chat.__call__."
    content: str
    tool_calls: list = field(default_factory=list)
    finish_reason: str = 'stop'
    model: str = ''

    def _repr_markdown_(self):
        md = self.content
        if self.tool_calls:
            md += '\n\n' + '\n'.join(f"🔧 {tc['name']}({tc.get('arguments',{})})" for tc in self.tool_calls)
        details = [f"model: `{self.model}`", f"finish_reason: `{self.finish_reason}`"]
        md += f"\n\n<details>\n\n- " + '\n- '.join(details) + '\n\n</details>'
        return md

# %% ../nbs/00_core.ipynb #88e0d714
_engines: dict = {}

def _get_engine(model_path: str) -> 'litert_lm._Engine':
    "Get or create a cached Engine for `model_path`. One Engine per model."
    p = os.path.abspath(model_path)
    if p not in _engines:
        _engines[p] = litert_lm.Engine(p)
        _engines[p].__enter__()
    return _engines[p]

def _close_engines():
    "Close all cached engines."
    for e in _engines.values():
        try: e.__exit__(None, None, None)
        except: pass
    _engines.clear()

atexit.register(_close_engines)

# %% ../nbs/00_core.ipynb #58ce5132
class Chat:
    def __init__(self, model_path: str, sp: str = '', tools: list = None,
                 hist: list = None, max_steps: int = 5, max_tokens: int = 1024):
        "LiteRT-LM stateful chat client."
        tools = listify(tools)
        hist = mk_msgs(hist) if hist else []
        store_attr()
        self._engine = _get_engine(model_path)
        self._init_conv()
        atexit.register(self.close)

    def _init_conv(self):
        msgs = []
        if self.sp: msgs.append({'role': 'system', 'content': [{'type': 'text', 'text': self.sp}]})
        msgs += self.hist
        self._conv = self._engine.create_conversation(messages=msgs, tools=self.tools or None)
        self._conv.__enter__()

    def __call__(self, pr=None) -> Response:
        "Send `pr` to model; return Response."
        if pr is not None:
            self.hist.append({'role': 'user', 'content': [{'type': 'text', 'text': pr}]})
        resp = self._conv.send_message(pr)
        text = get_text(resp)
        tcs = extract_tool_calls(text)
        asst = {'role': 'assistant', 'content': [{'type': 'text', 'text': text}]}
        if resp.get('tool_calls'): asst['tool_calls'] = resp['tool_calls']
        if resp.get('tool_responses'): asst['tool_responses'] = resp['tool_responses']
        self.hist.append(asst)
        fr = 'tool_calls' if tcs else 'stop'
        return Response(content=text, tool_calls=tcs, finish_reason=fr, model=self.model_path)

    @property
    def h(self): return self.hist

    def reset(self):
        "Clear history and recreate conversation (keeps engine alive)."
        self._close_conv()
        self.hist = []
        self._init_conv()

    def _close_conv(self):
        try: self._conv.__exit__(None, None, None)
        except: pass

    def close(self):
        "Close the conversation."
        self._close_conv()

    def __enter__(self): return self
    def __exit__(self, *exc): self.close()

# %% ../nbs/00_core.ipynb #8a546818
class AsyncChat(Chat):
    "Async streaming variant of Chat."

    @delegates(Chat.__init__)
    def __init__(self, **kwargs): super().__init__(**kwargs)

    async def __call__(self, pr=None):
        "Async generator: yields str chunks, then final Response."
        if pr is not None:
            self.hist.append({'role': 'user', 'content': [{'type': 'text', 'text': pr}]})
        loop = asyncio.get_event_loop()
        chunks_iter = await loop.run_in_executor(None, self._conv.send_message_async, pr)
        full = []
        for chunk in chunks_iter:
            for item in chunk.get('content', []):
                if item.get('type') == 'text':
                    t = item['text']
                    full.append(t)
                    yield t
        text = ''.join(full)
        tcs = extract_tool_calls(text)
        asst = {'role': 'assistant', 'content': [{'type': 'text', 'text': text}]}
        self.hist.append(asst)
        fr = 'tool_calls' if tcs else 'stop'
        yield Response(content=text, tool_calls=tcs, finish_reason=fr, model=self.model_path)

    async def acall(self, pr=None) -> Response:
        "Convenience: collect all chunks, return final Response."
        r = None
        async for chunk in self(pr):
            if isinstance(chunk, Response): r = chunk
        return r

    async def __aenter__(self): return self
    async def __aexit__(self, *exc): self.close()
